name: Build Hybris Operator Image
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      REGISTRY_USERNAME: ${{ secrets.QUAY_USERNAME }}
      REGISTRY_PASSWORD: ${{ secrets.QUAY_TOKEN }}
      OPERATOR_IMAGE: quay.io/xiezhang7/hybris-operator
      OPERATOR_TAG: 0.1
      BUNDLE_IMAGE: quay.io/xiezhang7/hybris-bundle
      BUNDLE_TAG: 0.1
      INDEX_IMAGE: quay.io/xiezhang7/hybris-index
      INDEX_TAG: 0.1
    steps:
      - name: Env
        run: |
          echo ${REGISTRY_USERNAME}
          echo ${OPERATOR_IMAGE}
          echo ${BUNDLE_IMAGE}
          echo ${INDEX_IMAGE}
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.13.0'
      - uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${REGISTRY_USERNAME}
          password: ${REGISTRY_PASSWORD}
      - uses: docker/setup-buildx-action@v1
        with:
          version: latest
      - uses: actions/checkout@v2
      - name: Install Kubebuilder
        run: |
          os=$(go env GOOS)
          arch=$(go env GOARCH)
          curl -L https://go.kubebuilder.io/dl/2.3.1/${os}/${arch} | tar -xz -C /tmp/
          sudo mv /tmp/kubebuilder_2.3.1_${os}_${arch} /usr/local/kubebuilder
      - name: Install Operator SDK
        env:
          RELEASE_VERSION: v1.0.0
        run: |
          curl -LO https://github.com/operator-framework/operator-sdk/releases/download/${RELEASE_VERSION}/operator-sdk-${RELEASE_VERSION}-x86_64-linux-gnu
          chmod +x operator-sdk-${RELEASE_VERSION}-x86_64-linux-gnu && sudo mkdir -p /usr/local/bin/ && sudo cp operator-sdk-${RELEASE_VERSION}-x86_64-linux-gnu /usr/local/bin/operator-sdk && rm operator-sdk-${RELEASE_VERSION}-x86_64-linux-gnu
      - name: Build and Push Operator
        run: |
          export PATH=$PATH:/usr/local/kubebuilder/bin
          make docker-build docker-push IMG=${OPERATOR_IMAGE}:${OPERATOR_TAG}
      - name: Podman Setup
        run: |
          podman login -u ${REGISTRY_USERNAME} -p ${REGISTRY_PASSWORD} quay.io
      - name: Install OPM
        env:
          RELEASE_VERSION: v1.13.8
        run: |
          curl -LO https://github.com/operator-framework/operator-registry/releases/download/${RELEASE_VERSION}/linux-amd64-opm
          chmod +x linux-amd64-opm && sudo mkdir -p /usr/local/bin/ && sudo cp linux-amd64-opm /usr/local/bin/opm && rm linux-amd64-opm
      - name: Build and Push Bundle
        run: |
          make bundle
          podman build -t ${BUNDLE_IMAGE}:${BUNDLE_TAG} -f bundle.Dockerfile .
          podman push ${BUNDLE_IMAGE}:${BUNDLE_TAG}
      - name: Build and Push Index
        run: |
          opm index add --bundles ${BUNDLE_IMAGE}:${BUNDLE_TAG} --tag ${INDEX_IMAGE}:${INDEX_TAG}
          podman push ${INDEX_IMAGE}:${INDEX_TAG}
      
